USE LunaLav;
GO
IF NOT EXISTS(SELECT 1 FROM sys.schemas WHERE name=N'core') EXEC(N'CREATE SCHEMA core');
IF NOT EXISTS(SELECT 1 FROM sys.schemas WHERE name=N'automation') EXEC(N'CREATE SCHEMA automation');
IF NOT EXISTS(SELECT 1 FROM sys.schemas WHERE name=N'agents') EXEC(N'CREATE SCHEMA agents');
IF NOT EXISTS(SELECT 1 FROM sys.schemas WHERE name=N'communication') EXEC(N'CREATE SCHEMA communication');
GO
IF OBJECT_ID(N'core.DomainEvent',N'U') IS NULL CREATE TABLE core.DomainEvent(
 Id BIGINT IDENTITY PRIMARY KEY, EventType NVARCHAR(120) NOT NULL, AggregateType NVARCHAR(80) NOT NULL, AggregateId NVARCHAR(80) NOT NULL,
 Payload NVARCHAR(MAX) NOT NULL, OccurredAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(), CorrelationId UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(), ProcessedAt DATETIME2 NULL);
IF NOT EXISTS(SELECT 1 FROM sys.indexes WHERE name=N'IX_CoreDomainEvent_Pending') CREATE INDEX IX_CoreDomainEvent_Pending ON core.DomainEvent(ProcessedAt,OccurredAt);
GO
IF OBJECT_ID(N'automation.Job',N'U') IS NULL CREATE TABLE automation.Job(
 Id BIGINT IDENTITY PRIMARY KEY, JobType NVARCHAR(120) NOT NULL, Payload NVARCHAR(MAX) NOT NULL, IdempotencyKey NVARCHAR(180) NOT NULL,
 Status NVARCHAR(20) NOT NULL DEFAULT N'PENDING', Attempts INT NOT NULL DEFAULT 0, MaxAttempts INT NOT NULL DEFAULT 5,
 AvailableAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(), LockedUntil DATETIME2 NULL, LastError NVARCHAR(2000) NULL,
 CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(), CompletedAt DATETIME2 NULL, CONSTRAINT UQ_AutomationJob_Idempotency UNIQUE(IdempotencyKey));
IF NOT EXISTS(SELECT 1 FROM sys.indexes WHERE name=N'IX_AutomationJob_Queue') CREATE INDEX IX_AutomationJob_Queue ON automation.Job(Status,AvailableAt,LockedUntil);
GO
IF OBJECT_ID(N'agents.AgentDefinition',N'U') IS NULL CREATE TABLE agents.AgentDefinition(
 Id INT IDENTITY PRIMARY KEY, Nombre NVARCHAR(80) NOT NULL, Departamento NVARCHAR(50) NOT NULL, Descripcion NVARCHAR(500) NULL,
 Autonomia TINYINT NOT NULL DEFAULT 1 CHECK(Autonomia BETWEEN 0 AND 4), Activo BIT NOT NULL DEFAULT 0, Provider NVARCHAR(50) NULL, Model NVARCHAR(100) NULL,
 DailyBudget DECIMAL(12,4) NULL, MonthlyBudget DECIMAL(12,4) NULL, CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID(N'agents.AgentRun',N'U') IS NULL CREATE TABLE agents.AgentRun(
 Id BIGINT IDENTITY PRIMARY KEY, AgentId INT NOT NULL REFERENCES agents.AgentDefinition(Id), Status NVARCHAR(20) NOT NULL,
 StartedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(), FinishedAt DATETIME2 NULL, InputSummary NVARCHAR(2000) NULL, ResultSummary NVARCHAR(4000) NULL,
 TokensIn INT NULL, TokensOut INT NULL, EstimatedCost DECIMAL(12,6) NULL, Error NVARCHAR(2000) NULL, CorrelationId UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID());
GO
IF OBJECT_ID(N'agents.Approval',N'U') IS NULL CREATE TABLE agents.Approval(
 Id BIGINT IDENTITY PRIMARY KEY, AgentId INT NULL REFERENCES agents.AgentDefinition(Id), ActionType NVARCHAR(100) NOT NULL, Payload NVARCHAR(MAX) NOT NULL,
 Risk NVARCHAR(20) NOT NULL, Status NVARCHAR(20) NOT NULL DEFAULT N'PENDING', Reason NVARCHAR(1000) NULL,
 RequestedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(), ReviewedBy NVARCHAR(120) NULL, ReviewedAt DATETIME2 NULL, DecisionNote NVARCHAR(1000) NULL);
GO
IF OBJECT_ID(N'communication.Mailbox',N'U') IS NULL CREATE TABLE communication.Mailbox(
 Id INT IDENTITY PRIMARY KEY, Address NVARCHAR(180) NOT NULL UNIQUE, Provider NVARCHAR(50) NOT NULL, Status NVARCHAR(30) NOT NULL DEFAULT N'NOT_CONFIGURED',
 DisplayName NVARCHAR(120) NULL, EncryptedCredentials NVARCHAR(MAX) NULL, LastSyncAt DATETIME2 NULL, CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID(N'communication.Suppression',N'U') IS NULL CREATE TABLE communication.Suppression(
 Id BIGINT IDENTITY PRIMARY KEY, Email NVARCHAR(180) NULL, Phone NVARCHAR(40) NULL, Reason NVARCHAR(40) NOT NULL, Source NVARCHAR(100) NULL,
 CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(), CONSTRAINT CK_CommunicationSuppression_Contact CHECK(Email IS NOT NULL OR Phone IS NOT NULL));
IF NOT EXISTS(SELECT 1 FROM sys.indexes WHERE name=N'IX_CommunicationSuppression_Email') CREATE INDEX IX_CommunicationSuppression_Email ON communication.Suppression(Email) WHERE Email IS NOT NULL;
GO
