import { HttpClient } from '@angular/common/http'; import { Injectable, inject } from '@angular/core'; import { environment } from '../../environments/environment';
export interface Prospect { id:number; nombreComercial:string; distrito?:string; telefono?:string; whatsapp?:string; email?:string; estado:string; prioridad:string; score:number; fuente:string; fechaUltimoContacto?:string; proximoSeguimiento?:string; tags:{id:number;nombre:string;color:string}[]; }
@Injectable({providedIn:'root'}) export class MarketingService { private http=inject(HttpClient); private url=`${environment.apiUrl}/marketing`;
  dashboard(){return this.http.get<any>(`${this.url}/dashboard`);} prospects(params:Record<string,string|number>={}){return this.http.get<any>(`${this.url}/prospects`,{params:params as any});} prospect(id:number){return this.http.get<any>(`${this.url}/prospects/${id}`);} changeStatus(id:number,estado:string){return this.http.patch(`${this.url}/prospects/${id}/estado`,{estado});} createActivity(id:number,body:any){return this.http.post(`${this.url}/prospects/${id}/activities`,body);} tags(){return this.http.get<any[]>(`${this.url}/tags`);} createProspect(body:any){return this.http.post<Prospect>(`${this.url}/prospects`,body);} followups(){return this.http.get<any[]>(`${this.url}/followups`);} createFollowup(body:any){return this.http.post(`${this.url}/followups`,body);} completeFollowup(id:number){return this.http.patch(`${this.url}/followups/${id}/complete`,{});} tasks(){return this.http.get<any[]>(`${this.url}/tasks`);} createTask(body:any){return this.http.post(`${this.url}/tasks`,body);} completeTask(id:number){return this.http.patch(`${this.url}/tasks/${id}/complete`,{});}
  campaigns(){return this.http.get<any[]>(`${this.url}/campaigns`);} createCampaign(body:any){return this.http.post(`${this.url}/campaigns`,body);} campaignStatus(id:number,estado:string){return this.http.patch(`${this.url}/campaigns/${id}/status`,{estado});}
  drafts(){return this.http.get<any[]>(`${this.url}/drafts`);} createDraft(body:any){return this.http.post(`${this.url}/drafts`,body);} draftStatus(id:number,estado:string){return this.http.patch(`${this.url}/drafts/${id}/status`,{estado});}
  generarPublicacionIA(body:any){return this.http.post<any>(`${this.url}/publicaciones/generar`,body);}
  agentSettings(){return this.http.get<any>(`${this.url}/agent-settings`);} saveAgentSettings(body:any){return this.http.put(`${this.url}/agent-settings`,body);}
  agentStatus(){return this.http.get<any>(`${this.url}/automation/status`);} automationRules(){return this.http.get<any[]>(`${this.url}/automation/rules`);} setAutomationRule(id:number,activa:boolean){return this.http.patch(`${this.url}/automation/rules/${id}`,activa);}
  approvals(){return this.http.get<any[]>(`${this.url}/automation/approvals`);} decideApproval(id:number,estado:'APPROVED'|'REJECTED'){return this.http.patch(`${this.url}/automation/approvals/${id}`,{estado});} runAutomation(type:string){return this.http.post(`${this.url}/automation/jobs/${type}`,{});}
  googleStatus(){return this.http.get<any>(`${this.url}/google/status`);} startGmailConnect(){return this.http.post<any>(`${this.url}/google/gmail/connect`,{});} syncGmail(){return this.http.post<any>(`${this.url}/google/gmail/sync`,{});} inboxMessages(){return this.http.get<any[]>(`${this.url}/google/gmail/inbox`);} searchPlaces(q:string,max=10){return this.http.get<any[]>(`${this.url}/google/places/search`,{params:{q,max}});} searchPlacesAround(lat:number,lng:number,max=15){return this.http.get<any[]>(`${this.url}/google/places/search`,{params:{lat,lng,max}});}
}
