import { Component, OnInit, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { RouterLink } from '@angular/router';
import { MarketingService, Prospect } from './marketing.service';

@Component({ standalone:true, imports:[FormsModule,RouterLink], template:`
<div class="head"><div><h1>Prospectos</h1><p>Gestiona y da seguimiento a tus oportunidades comerciales.</p></div><a routerLink="/marketing/prospectos/nuevo">＋ Nuevo prospecto</a></div>
<section class="tabs"><button class="active">Todos <b>({{total()}})</b></button><button (click)="estado='NUEVO';buscar()">Nuevos</button><button (click)="estado='CONTACTADO';buscar()">Contactados</button><button (click)="estado='INTERESADO';buscar()">Interesados</button><button (click)="estado='DEMO_PROGRAMADA';buscar()">Demo</button><button (click)="estado='';buscar()">Limpiar</button></section>
<section class="filters"><label>⌕ <input [(ngModel)]="q" (ngModelChange)="buscar()" placeholder="Buscar prospectos…"></label><select [(ngModel)]="estado" (ngModelChange)="buscar()"><option value="">Todos los estados</option><option value="NUEVO">Nuevo</option><option value="INVESTIGAR">Investigar</option><option value="CONTACTADO">Contactado</option><option value="INTERESADO">Interesado</option><option value="DEMO_PROGRAMADA">Demo</option><option value="GANADO">Ganado</option></select><button class="filter-btn">⌘ Filtros</button></section>
<section class="table">@if(cargando()){<p>Cargando prospectos…</p>}@else if(items().length===0){<div class="empty"><h2>Todavía no tienes prospectos</h2><p>Empieza registrando una lavandería potencial para LunaLav.</p><a routerLink="/marketing/prospectos/nuevo">Crear primer prospecto</a></div>}@else{<div class="row th"><span>Negocio</span><span>Distrito</span><span>Estado</span><span>Score</span><span>Próxima acción</span></div>@for(x of items();track x.id){<a class="row" [routerLink]="['/marketing/prospectos',x.id]"><span><b>{{x.nombreComercial}}</b><small>{{x.whatsapp||x.telefono||x.email||'Sin contacto'}}</small></span><span>{{x.distrito||'—'}}</span><span><i>{{x.estado.replaceAll('_',' ')}}</i></span><span><strong>{{x.score}}</strong><small>/100</small></span><span>{{x.proximoSeguimiento ? 'Programado' : 'Sin programar'}}</span></a>}<footer>{{total()}} prospectos registrados</footer>}</section>`,
styles:[`.head{display:flex;justify-content:space-between;gap:20px;align-items:start}.head h1{margin:0 0 4px;font-size:28px;letter-spacing:-1px}.head p{margin:0;color:#6b88a9;font-size:14px}.head>a,.empty a{background:linear-gradient(135deg,#119cf2,#177de3);color:#fff;text-decoration:none;border-radius:8px;padding:11px 15px;font-weight:800;font-size:13px;box-shadow:0 6px 14px #188bea33}.tabs{display:flex;gap:5px;margin:22px 0 11px;padding:5px;background:#fff;border:1px solid #dcecf8;border-radius:9px;width:max-content;max-width:100%;overflow:auto}.tabs button{border:0;background:transparent;border-radius:6px;padding:8px 13px;color:#6380a0;font-size:12px;white-space:nowrap}.tabs button.active{background:#e0f3ff;color:#138ae7;font-weight:800}.filters{display:flex;gap:10px;margin:0 0 14px}.filters label{display:flex;align-items:center;gap:8px;flex:1;max-width:410px;background:#fff;border:1px solid #dcebf7;border-radius:8px;padding:0 11px;color:#7795b1}.filters input{width:100%;border:0;outline:0;padding:11px 0;background:transparent;font-size:13px}.filters select,.filter-btn{background:#fff;border:1px solid #dcebf7;border-radius:8px;padding:10px 12px;font-size:12px;color:#526f90}.table{background:#fff;border:1px solid #dcecf8;border-radius:12px;overflow:hidden;box-shadow:0 5px 17px #2b6da00c}.row{display:grid;grid-template-columns:2fr 1fr 1.2fr .7fr 1.3fr;gap:10px;padding:14px 17px;align-items:center;border-bottom:1px solid #edf4fa;text-decoration:none;color:#213f68;font-size:13px}.row:not(.th):hover{background:#f4fbff}.th{font-size:10px;color:#7894b0;text-transform:uppercase;font-weight:900;background:#f9fcff}.row span:first-child{display:grid;gap:3px}.row span:first-child b:before{content:'◒';display:inline-grid;place-items:center;margin-right:9px;width:23px;height:23px;border-radius:6px;background:#e4f2ff;color:#1488e6}.row small{font-size:11px;color:#7890a4}.row i{font-style:normal;font-size:10px;font-weight:800;padding:5px 8px;border-radius:99px;background:#e5f3ff;color:#2584c8}.row strong{color:#087cc1}.empty{text-align:center;padding:64px 20px}.empty h2{font-size:19px}.empty p{color:#71869b;margin-bottom:24px}footer{padding:12px 17px;font-size:12px;color:#7890a4}@media(max-width:800px){.row{grid-template-columns:2fr 1fr .7fr}.row span:nth-child(2),.row span:nth-child(5){display:none}.head{align-items:center}.head p{display:none}.filter-btn{display:none}}`]
}) export class MarketingProspectsComponent implements OnInit {private svc=inject(MarketingService);items=signal<Prospect[]>([]);total=signal(0);cargando=signal(true);q='';estado='';ngOnInit(){this.buscar();}buscar(){this.cargando.set(true);this.svc.prospects({q:this.q,estado:this.estado}).subscribe({next:x=>{this.items.set(x.items);this.total.set(x.total);this.cargando.set(false)},error:()=>this.cargando.set(false)});}}
