import { Component, OnInit, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { MarketingService } from './marketing.service';

@Component({
  standalone:true,
  imports:[RouterLink,FormsModule],
  template:`@if(data()){<a routerLink="/marketing/prospectos">← Prospectos</a>
  <div class="head"><div><span>{{data().resumen.estado.replaceAll('_',' ')}}</span><h1>{{data().resumen.nombreComercial}}</h1><p>{{data().resumen.distrito||'Distrito pendiente'}} · Score {{data().resumen.score}}/100</p></div><select (change)="estado($any($event.target).value)">@for(e of estados;track e){<option [selected]="e===data().resumen.estado" [value]="e">{{e.replaceAll('_',' ')}}</option>}</select></div>
  <div class="quick-actions"><a class="qa call" [class.off]="!phone()" [href]="phone()?'tel:'+phone():null">📞 Llamar</a><a class="qa wa" [class.off]="!wa()" [href]="wa()?'https://wa.me/'+wa():null" target="_blank" rel="noopener">💬 WhatsApp</a><a class="qa mail" [class.off]="!data().resumen.email" [href]="data().resumen.email?'mailto:'+data().resumen.email:null">✉ Email</a>@if(data().sitioWeb){<a class="qa web" [href]="data().sitioWeb" target="_blank" rel="noopener">🌐 Web</a>}<button class="qa follow" (click)="programar()" [disabled]="saving()">🗓 Programar seguimiento</button></div>
  <div class="grid"><section><article class="card"><h2>Información comercial</h2><dl><dt>Teléfono</dt><dd>{{data().resumen.telefono||'No registrado'}}</dd><dt>WhatsApp</dt><dd>{{data().resumen.whatsapp||'No registrado'}}</dd><dt>Email</dt><dd>{{data().resumen.email||'No registrado'}}</dd><dt>Dirección</dt><dd>{{data().direccion||'No registrada'}}</dd><dt>Web</dt><dd>{{data().sitioWeb||'No registrada'}}</dd><dt>Delivery</dt><dd>{{data().tieneDelivery?'Sí':'No confirmado'}}</dd><dt>Forma de trabajo</dt><dd>{{data().formaTrabajoActual}}</dd></dl></article><article class="card"><h2>Actividad</h2><form class="note-form" (ngSubmit)="agregarNota()"><input [(ngModel)]="nota" name="nota" placeholder="Añadir nota o registro de contacto…" maxlength="2000"><button [disabled]="!nota.trim()||saving()">Agregar</button></form>@for(a of data().actividades;track a.id){<div class="activity"><b>{{a.titulo}}</b><p>{{a.detalle||a.tipo}}</p><small>{{a.usuario||'Equipo LunaLav'}}</small></div>}@empty{<p class="muted">Aún no hay actividad registrada. Agrega una nota arriba.</p>}</article></section><aside class="card"><h2>Próximos seguimientos</h2>@for(f of data().seguimientos;track f.id){<div class="follow"><b>{{f.tipo}}</b><p>{{f.descripcion}}</p><small>{{f.completado?'Completado':'Pendiente'}}</small></div>}@empty{<p class="muted">Sin seguimientos. Usa "Programar seguimiento".</p>}</aside></div>}`,
  styles:[`:host{display:block;max-width:1180px}:host>a{font-size:13px;color:#087cc1;text-decoration:none;font-weight:800}.head{display:flex;justify-content:space-between;align-items:start;margin:20px 0 14px}.head span{font-size:11px;font-weight:900;color:#168bcb}.head h1{margin:7px 0;font-size:30px}.head p,.muted{color:#71869b}.head select{padding:10px;border:1px solid #d5e1eb;border-radius:8px}.quick-actions{display:flex;gap:9px;flex-wrap:wrap;margin-bottom:18px}.qa{display:inline-flex;align-items:center;gap:6px;border:1px solid #cfe6fb;background:#fff;color:#127bd6;border-radius:9px;padding:10px 14px;font-size:12px;font-weight:800;text-decoration:none;cursor:pointer}.qa:hover{background:#f2f9ff}.qa.wa{border-color:#bfe9cf;color:#1a9d55}.qa.follow{background:#168dea;color:#fff;border-color:#168dea}.qa.off{opacity:.45;pointer-events:none}.qa:disabled{opacity:.5;cursor:not-allowed}.grid{display:grid;grid-template-columns:1.4fr .8fr;gap:18px}.card{background:#fff;border:1px solid #e1e9f1;border-radius:12px;padding:20px;margin-bottom:18px}.card h2{font-size:16px;margin:0 0 15px}dl{display:grid;grid-template-columns:150px 1fr;gap:12px;margin:0;font-size:13px}dt{color:#71869b}dd{margin:0}.note-form{display:flex;gap:8px;margin-bottom:14px}.note-form input{flex:1;border:1px solid #dcebf7;border-radius:8px;padding:10px;font:inherit;font-size:12px}.note-form button{border:0;background:#168dea;color:#fff;border-radius:8px;padding:0 15px;font-size:12px;font-weight:800;cursor:pointer}.note-form button:disabled{opacity:.5;cursor:not-allowed}.activity,.follow{padding:13px 0;border-top:1px solid #edf1f5;font-size:13px}.activity p,.follow p{margin:4px 0;color:#627a90}.activity small,.follow small{color:#2182bc;font-size:11px}@media(max-width:800px){.grid{grid-template-columns:1fr}.head{align-items:end}}`]
})
export class MarketingProspectDetailComponent implements OnInit {
  private svc=inject(MarketingService);private route=inject(ActivatedRoute);
  data=signal<any>(null);saving=signal(false);nota='';id=0;
  estados=['NUEVO','INVESTIGAR','LISTO_CONTACTAR','CONTACTADO','RESPONDIO','INTERESADO','DEMO_PROGRAMADA','DEMO_REALIZADA','NEGOCIACION','GANADO','PERDIDO'];
  ngOnInit(){this.id=Number(this.route.snapshot.paramMap.get('id'));this.cargar();}
  cargar(){this.svc.prospect(this.id).subscribe(x=>this.data.set(x));}
  estado(e:string){this.svc.changeStatus(this.id,e).subscribe(()=>this.cargar());}
  phone(){return this.data()?.resumen?.telefono || this.data()?.resumen?.whatsapp || '';}
  wa(){const raw=(this.data()?.resumen?.whatsapp||this.data()?.resumen?.telefono||'').replace(/\D/g,'');return raw?(raw.length===9?'51'+raw:raw):'';}
  agregarNota(){const t=this.nota.trim();if(!t||this.saving())return;this.saving.set(true);this.svc.createActivity(this.id,{tipo:'NOTA',titulo:'Nota',detalle:t}).subscribe({next:()=>{this.nota='';this.saving.set(false);this.cargar();},error:()=>this.saving.set(false)});}
  programar(){if(this.saving())return;this.saving.set(true);this.svc.createFollowup({prospectId:this.id,tipo:'LLAMADA',prioridad:'MEDIA',descripcion:`Seguimiento a ${this.data()?.resumen?.nombreComercial||'prospecto'}`,fechaProgramada:new Date(Date.now()+86400000).toISOString()}).subscribe({next:()=>{this.saving.set(false);this.cargar();},error:()=>this.saving.set(false)});}
}
