import { Component, OnDestroy, OnInit, inject, signal } from '@angular/core';
import { DatePipe } from '@angular/common';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { FormsModule } from '@angular/forms';
import { MarketingService } from './marketing.service';

@Component({
  standalone:true,
  imports:[FormsModule,RouterLink,DatePipe],
  templateUrl:'./marketing-modules.component.html',
  styleUrls:['./marketing-modules.component.css']
})
export class MarketingModulesComponent implements OnInit, OnDestroy {
  private route=inject(ActivatedRoute); private svc=inject(MarketingService); mode='';q='';district='';prospects=signal<any[]>([]);campaigns=signal<any[]>([]);drafts=signal<any[]>([]);followups=signal<any[]>([]);summary=signal<any>(null);agent=signal<any>(null);showForm=signal(false);
  campaign:any={nombre:'',audiencia:'',canal:'EMAIL',asunto:'',mensaje:''};draft:any={canal:'EMAIL',destinatario:'',asunto:'',cuerpo:''};google=signal<any>(null);exporting=signal(false);agentStatus=signal<any>(null);private timer:any;
  descZona='';descMax=15;descLoading=signal(false);descResult=signal<any>(null);
  descubrir(){if(this.descLoading())return;this.descLoading.set(true);this.descResult.set(null);this.svc.descubrirProspectos({zona:this.descZona,max:this.descMax}).subscribe({next:r=>{this.descLoading.set(false);this.descResult.set(r);},error:e=>{this.descLoading.set(false);this.descResult.set({error:e.error?.mensaje||'No se pudo buscar. Intenta de nuevo en unos segundos.'});}});}
  pub:any={tipo:'promo',temporada:'ninguna',negocio:'LunaLav',oferta:'',zona:'',contacto:'',emojis:true,modelo:'qwen3:8b'};postText='';
  readonly modelos:{id:string,label:string}[]=[{id:'qwen3:8b',label:'Qwen3 8B · mejor redacción'},{id:'llama3.2:latest',label:'Llama 3.2 · más rápido'},{id:'llama3.1:8b',label:'Llama 3.1 8B'},{id:'gemma4:latest',label:'Gemma'}];copiado=signal(false);historial=signal<any[]>([]);private histKey='lunalav.pub.historial';iaLoading=signal(false);iaMsg=signal('');imagenUrl=signal('');
  calView=signal<'mes'|'semana'|'dia'>('mes');calCursor=signal<Date>(new Date());calSelected=signal<Date>(new Date());
  calFollowups=signal<any[]>([]);calTasks=signal<any[]>([]);calProspects=signal<any[]>([]);
  nuevoSeg:any={prospectId:null,hora:'',prioridad:'MEDIA',descripcion:''};segSaving=signal(false);segMsg=signal('');
  readonly diasSemana=['Lun','Mar','Mié','Jue','Vie','Sáb','Dom'];
  private readonly meses=['Enero','Febrero','Marzo','Abril','Mayo','Junio','Julio','Agosto','Septiembre','Octubre','Noviembre','Diciembre'];
  private readonly diasFull=['Domingo','Lunes','Martes','Miércoles','Jueves','Viernes','Sábado'];
  setVista(v:'mes'|'semana'|'dia'){this.calView.set(v);if(v==='dia')this.calSelected.set(new Date(this.calCursor()));}
  calMove(n:number){const d=new Date(this.calCursor());const v=this.calView();if(v==='mes')d.setMonth(d.getMonth()+n);else if(v==='semana')d.setDate(d.getDate()+7*n);else d.setDate(d.getDate()+n);this.calCursor.set(d);if(v==='dia')this.calSelected.set(new Date(d));}
  calHoy(){const t=new Date();this.calCursor.set(t);this.calSelected.set(new Date(t));}
  selDia(d:Date){this.calSelected.set(new Date(d));}
  private calKey(d:Date){return `${d.getFullYear()}-${d.getMonth()}-${d.getDate()}`;}
  selKey(){return this.calKey(this.calSelected());}
  calLabel(){const d=this.calCursor(),v=this.calView();if(v==='mes')return `${this.meses[d.getMonth()]} ${d.getFullYear()}`;if(v==='dia')return `${this.diasFull[d.getDay()]} ${d.getDate()} ${this.meses[d.getMonth()]} ${d.getFullYear()}`;const wk=this.semanaDias(d),a=wk[0],b=wk[6];return `${a.getDate()} ${this.meses[a.getMonth()].slice(0,3)} – ${b.getDate()} ${this.meses[b.getMonth()].slice(0,3)} ${b.getFullYear()}`;}
  selLabel(){const d=this.calSelected();return `${this.diasFull[d.getDay()]} ${d.getDate()} de ${this.meses[d.getMonth()]}`;}
  selShort(){const d=this.calSelected();return `${d.getDate()}/${d.getMonth()+1}`;}
  private hora(d:Date){const h=d.getHours(),m=d.getMinutes();return (h||m)?`${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}`:'';}
  private calEventos(){const evs:any[]=[];for(const f of this.calFollowups()){if(!f.fechaProgramada)continue;const dt=new Date(f.fechaProgramada);evs.push({id:'f'+f.id,date:dt,hora:this.hora(dt),kind:'seguimiento',title:f.negocio||'Seguimiento',sub:`${f.tipo||''} · ${f.descripcion||''}`,prioridad:f.prioridad,prospectId:f.prospectId});}for(const t of this.calTasks()){if(!t.fechaVencimiento)continue;const dt=new Date(t.fechaVencimiento);evs.push({id:'t'+t.id,date:dt,hora:this.hora(dt),kind:'tarea',title:t.negocio||t.titulo||'Tarea',sub:t.titulo||'',prioridad:t.prioridad,prospectId:t.prospectId});}return evs;}
  private eventosDia(d:Date){const k=this.calKey(d);return this.calEventos().filter(e=>this.calKey(e.date)===k).sort((a,b)=>(a.hora||'99').localeCompare(b.hora||'99'));}
  selEventos(){return this.eventosDia(this.calSelected());}
  diaEventos(){return this.eventosDia(this.calCursor());}
  private semanaDias(ref:Date){const dow=(ref.getDay()+6)%7;const start=new Date(ref);start.setDate(start.getDate()-dow);const out:Date[]=[];for(let i=0;i<7;i++){out.push(new Date(start));start.setDate(start.getDate()+1);}return out;}
  calWeek(){const tkey=this.calKey(new Date());const byday:Record<string,any[]>={};for(const e of this.calEventos()){const k=this.calKey(e.date);(byday[k]=byday[k]||[]).push(e);}return this.semanaDias(this.calCursor()).map(d=>{const k=this.calKey(d);return {key:k,date:d,day:d.getDate(),dow:this.diasSemana[(d.getDay()+6)%7],isToday:k===tkey,events:(byday[k]||[]).sort((a,b)=>(a.hora||'99').localeCompare(b.hora||'99'))};});}
  calGrid(){const cur=this.calCursor();const first=new Date(cur.getFullYear(),cur.getMonth(),1);const month=first.getMonth();const dow=(first.getDay()+6)%7;const start=new Date(first);start.setDate(start.getDate()-dow);const daysInMonth=new Date(first.getFullYear(),month+1,0).getDate();const total=Math.ceil((dow+daysInMonth)/7)*7;const tkey=this.calKey(new Date());const byday:Record<string,any[]>={};for(const e of this.calEventos()){const k=this.calKey(e.date);(byday[k]=byday[k]||[]).push(e);}const cells:any[]=[];const c=new Date(start);for(let i=0;i<total;i++){const k=this.calKey(c);cells.push({key:k,date:new Date(c),day:c.getDate(),inMonth:c.getMonth()===month,isToday:k===tkey,events:(byday[k]||[]).sort((a,b)=>(a.hora||'99').localeCompare(b.hora||'99'))});c.setDate(c.getDate()+1);}return cells;}
  crearSeguimiento(){if(!this.nuevoSeg.prospectId||!this.nuevoSeg.descripcion||this.segSaving())return;const d=new Date(this.calSelected());const t=(this.nuevoSeg.hora||'09:00').split(':');d.setHours(+t[0]||9,+t[1]||0,0,0);this.segSaving.set(true);this.segMsg.set('');this.svc.createFollowup({prospectId:this.nuevoSeg.prospectId,tipo:'LLAMADA',prioridad:this.nuevoSeg.prioridad,descripcion:this.nuevoSeg.descripcion,fechaProgramada:d.toISOString()}).subscribe({next:()=>{this.segSaving.set(false);this.segMsg.set('Seguimiento agendado ✔');this.nuevoSeg={prospectId:null,hora:'',prioridad:'MEDIA',descripcion:''};this.svc.followups().subscribe(x=>this.calFollowups.set(x));},error:e=>{this.segSaving.set(false);this.segMsg.set(e.error?.mensaje||'No se pudo agendar.');}});}
  readonly temporadas:{id:string,label:string}[]=[{id:'ninguna',label:'Sin temporada'},{id:'navidad',label:'🎄 Navidad'},{id:'anionuevo',label:'🎆 Año Nuevo'},{id:'fiestaspatrias',label:'🇵🇪 Fiestas Patrias'},{id:'sanvalentin',label:'❤️ San Valentín'},{id:'diamadre',label:'💐 Día de la Madre'},{id:'blackfriday',label:'🖤 Black Friday'}];
  private readonly tempData:Record<string,{emoji:string,frase:string,tags:string[]}>={ninguna:{emoji:'',frase:'',tags:[]},navidad:{emoji:'🎄',frase:'En Navidad tu lavandería recibe más pedidos: contrólalos sin estrés.',tags:['#Navidad']},anionuevo:{emoji:'🎆',frase:'Empieza el año con tu lavandería ordenada y digital.',tags:['#AñoNuevo']},fiestaspatrias:{emoji:'🇵🇪',frase:'En Fiestas Patrias atiende más rápido y sin errores.',tags:['#FiestasPatrias','#Perú']},sanvalentin:{emoji:'❤️',frase:'San Valentín trae más ropa a lavar: no pierdas ningún pedido.',tags:['#SanValentín']},diamadre:{emoji:'💐',frase:'El Día de la Madre tu lavandería se llena: que no colapse.',tags:['#DíaDeLaMadre']},blackfriday:{emoji:'🖤',frase:'¡Black Friday! Digitaliza tu lavandería con una oferta especial.',tags:['#BlackFriday','#Ofertas']}};
  private readonly jobNames:Record<string,string>={MARKETING_SCORE_RECALCULATION:'Recalcular scores',MARKETING_FOLLOWUP_REVIEW:'Revisar seguimientos vencidos',MARKETING_PREPARE_OUTREACH:'Preparar contactos'};
  jobLabel(t:string){return this.jobNames[t]||t.replaceAll('_',' ');}
  loadAgentStatus(){this.svc.agentStatus().subscribe(x=>this.agentStatus.set(x));}
  runNow(type:string){this.svc.runAutomation(type).subscribe(()=>setTimeout(()=>this.loadAgentStatus(),1500));}
  ngOnDestroy(){if(this.timer)clearInterval(this.timer);}
  ngOnInit(){this.mode=this.route.snapshot.data['mode'];if(this.mode==='explorar')this.loadExplore();if(this.mode==='campanas')this.loadCampaigns();if(this.mode==='inbox')this.loadDrafts();if(this.mode==='calendario'){this.svc.followups().subscribe(x=>this.calFollowups.set(x));this.svc.tasks().subscribe(x=>this.calTasks.set(x));this.svc.prospects({pageSize:200}).subscribe(x=>this.calProspects.set(x.items));}if(this.mode==='reportes')this.svc.dashboard().subscribe(x=>this.summary.set(x));if(this.mode==='agentes'){this.svc.agentSettings().subscribe(x=>this.agent.set(x));this.loadAgentStatus();this.timer=setInterval(()=>this.loadAgentStatus(),30000);}if(this.mode==='configuracion')this.svc.googleStatus().subscribe(x=>this.google.set(x));if(this.mode==='publicaciones'){this.generarPost();this.cargarHistorial();}}
  generarPost(){const e=this.pub.emojis;const n=(this.pub.negocio||'nuestra lavandería').trim();const o=(this.pub.oferta||'').trim();const z=(this.pub.zona||'').trim();const c=(this.pub.contacto||'').trim();const t=this.tempData[this.pub.temporada]||this.tempData['ninguna'];let cuerpo='';
    switch(this.pub.tipo){
      case 'promo':cuerpo=`${e?'🧺✨ ':''}¿Tienes una lavandería? Ordénala con ${n}.\n\nControla pedidos, clientes y cobros en un solo lugar${z?(' — '+z):''}. ${o||'Pídenos una demo gratis.'}`;break;
      case 'novedad':cuerpo=`${e?'🚀 ':''}Novedad en ${n}\n\n${o||'Nueva función para gestionar tu lavandería más fácil'}. El sistema que ordena tu negocio.`;break;
      case 'consejo':cuerpo=`${e?'💡 ':''}Tip para tu lavandería\n\n${o||'Lleva el control de cada pedido y cliente para no perder ventas ni prendas.'}\n\n${n} lo automatiza por ti.`;break;
      default:cuerpo=`${e?'⭐⭐⭐⭐⭐ ':''}"${o||('Desde que uso '+n+' controlo mi lavandería desde el celular y ya no pierdo pedidos.')}"\n\n— Dueño de lavandería que usa ${n}.`;
    }
    const temporada=t.frase?`${e&&t.emoji?t.emoji+' ':''}${t.frase}\n\n`:'';
    const cta=c?`\n\n${e?'📲 ':''}Escríbenos: ${c}`:'';
    this.postText=`${temporada}${cuerpo}${cta}\n\n${this.hashtags()}`.replace(/\n{3,}/g,'\n\n').trim();this.copiado.set(false);}
  private hashtags(){const t=['#Lavanderias','#GestiónDeLavandería',`#${(this.pub.negocio||'LunaLav').replace(/[^\p{L}\p{N}]/gu,'')||'LunaLav'}`];const z=(this.pub.zona||'').replace(/[^\p{L}\p{N}]/gu,'');if(z)t.push('#'+z);if(this.pub.tipo==='promo')t.push('#SoftwareParaLavanderías','#Demo');if(this.pub.tipo==='consejo')t.push('#Tips');t.push(...(this.tempData[this.pub.temporada]?.tags||[]));return [...new Set(t)].join(' ');}
  copiarPost(){const done=()=>{this.copiado.set(true);this.guardarHistorial();setTimeout(()=>this.copiado.set(false),2000);};if(navigator.clipboard?.writeText){navigator.clipboard.writeText(this.postText).then(done).catch(()=>this.fallbackCopy(done));}else this.fallbackCopy(done);}
  cargarHistorial(){try{const raw=localStorage.getItem(this.histKey);this.historial.set(raw?JSON.parse(raw):[]);}catch{this.historial.set([]);}}
  guardarHistorial(){const txt=this.postText.trim();if(!txt)return;const h=[{texto:txt,fecha:new Date().toISOString()},...this.historial().filter((x:any)=>x.texto!==txt)].slice(0,20);this.historial.set(h);try{localStorage.setItem(this.histKey,JSON.stringify(h));}catch{}}
  generarIA(){if(this.iaLoading())return;this.iaLoading.set(true);this.iaMsg.set('Generando con IA local (puede tardar unos segundos)…');this.svc.generarPublicacionIA({tipo:this.pub.tipo,temporada:this.pub.temporada,negocio:this.pub.negocio,oferta:this.pub.oferta,zona:this.pub.zona,contacto:this.pub.contacto,emojis:this.pub.emojis,modelo:this.pub.modelo}).subscribe({next:r=>{if(r?.texto)this.postText=r.texto;this.iaLoading.set(false);this.iaMsg.set('✔ Texto generado con IA. Puedes editarlo antes de publicar.');this.copiado.set(false);},error:e=>{this.iaLoading.set(false);this.iaMsg.set(e.error?.mensaje||'La IA local no está disponible ahora. Se mantiene el texto de plantilla.');}});}
  onImagen(e:any){const f=e.target.files?.[0];if(!f)return;if(!f.type.startsWith('image/')){this.iaMsg.set('El archivo debe ser una imagen.');return;}if(f.size>10*1024*1024){this.iaMsg.set('La imagen supera 10 MB.');return;}const r=new FileReader();r.onload=()=>this.imagenUrl.set(String(r.result||''));r.readAsDataURL(f);e.target.value='';}
  quitarImagen(){this.imagenUrl.set('');}
  descargarImagen(){const u=this.imagenUrl();if(!u)return;const a=document.createElement('a');a.href=u;a.download='publicacion-lunalav.png';document.body.appendChild(a);a.click();a.remove();}
  usarHistorial(x:any){this.postText=x.texto;this.copiado.set(false);}
  borrarHistorial(i:number){const h=this.historial().slice();h.splice(i,1);this.historial.set(h);try{localStorage.setItem(this.histKey,JSON.stringify(h));}catch{}}
  private fallbackCopy(done:()=>void){const ta=document.createElement('textarea');ta.value=this.postText;document.body.appendChild(ta);ta.select();try{document.execCommand('copy');done();}catch{}document.body.removeChild(ta);}
  waShare(){return 'https://wa.me/?text='+encodeURIComponent(this.postText);}
  fbShare(){return 'https://www.facebook.com/sharer/sharer.php?u='+encodeURIComponent('https://lunalav.pe')+'&quote='+encodeURIComponent(this.postText);}
  twShare(){return 'https://twitter.com/intent/tweet?text='+encodeURIComponent(this.postText);}
  loadExplore(){this.svc.prospects({q:this.q,distrito:this.district,pageSize:100}).subscribe(x=>this.prospects.set(x.items));} loadCampaigns(){this.svc.campaigns().subscribe(x=>this.campaigns.set(x));} loadDrafts(){this.svc.drafts().subscribe(x=>this.drafts.set(x));}
  createCampaign(){this.svc.createCampaign(this.campaign).subscribe({next:()=>{this.campaign={nombre:'',audiencia:'',canal:'EMAIL',asunto:'',mensaje:''};this.showForm.set(false);this.loadCampaigns();}});}campaignState(id:number,estado:string){this.svc.campaignStatus(id,estado).subscribe(()=>this.loadCampaigns());}
  createDraft(){this.svc.createDraft(this.draft).subscribe({next:()=>{this.draft={canal:'EMAIL',destinatario:'',asunto:'',cuerpo:''};this.showForm.set(false);this.loadDrafts();}});}draftState(id:number,estado:string){this.svc.draftStatus(id,estado).subscribe(()=>this.loadDrafts());}connectGmail(){this.svc.startGmailConnect().subscribe({next:x=>location.assign(x.authorizationUrl),error:e=>alert(e.error?.mensaje||'No se pudo iniciar Gmail.')});}saveAgent(){this.svc.saveAgentSettings(this.agent()).subscribe();}ratio(n:number){return this.summary()?.prospectosTotales?Math.max(8,Math.round(n*100/this.summary().prospectosTotales)):8;}
  pct(a:number,b:number){return b?Math.round((a||0)*100/b):0;}
  exportCsv(){this.exporting.set(true);this.svc.prospects({pageSize:2000}).subscribe({next:(x:any)=>{const rows=x.items||[];const head=['Negocio','Distrito','Telefono','WhatsApp','Email','Estado','Prioridad','Score','Fuente','UltimoContacto','ProximoSeguimiento','Etiquetas'];const esc=(v:any)=>{const s=v==null?'':String(v);return /[";\n]/.test(s)?'"'+s.replace(/"/g,'""')+'"':s;};const lines=[head.join(';')];for(const r of rows)lines.push([r.nombreComercial,r.distrito,r.telefono,r.whatsapp,r.email,r.estado,r.prioridad,r.score,r.fuente,r.fechaUltimoContacto?new Date(r.fechaUltimoContacto).toLocaleDateString():'',r.proximoSeguimiento?new Date(r.proximoSeguimiento).toLocaleDateString():'',(r.tags||[]).map((t:any)=>t.nombre).join(' | ')].map(esc).join(';'));const blob=new Blob(['﻿'+lines.join('\r\n')],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`prospectos-lunalav-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(url);this.exporting.set(false);},error:()=>this.exporting.set(false)});}
}
