import { Component, OnInit, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { RouterLink } from '@angular/router';
import { MarketingService, Prospect } from './marketing.service';

@Component({ standalone:true, imports:[FormsModule,RouterLink], template:`
<div class="head"><div><span>BASE COMERCIAL</span><h1>Prospectos</h1><p>Negocios evaluados por el equipo. Guarda fuente e interacciones.</p></div><a routerLink="/marketing/prospectos/nuevo">+ Agregar prospecto</a></div>
<section class="filters"><input [(ngModel)]="q" (ngModelChange)="buscar()" placeholder="Buscar negocio, teléfono o distrito"><select [(ngModel)]="estado" (ngModelChange)="buscar()"><option value="">Todos los estados</option><option value="NUEVO">Nuevo</option><option value="INVESTIGAR">Investigar</option><option value="CONTACTADO">Contactado</option><option value="INTERESADO">Interesado</option><option value="DEMO_PROGRAMADA">Demo</option><option value="GANADO">Ganado</option></select></section>
<section class="table">@if(cargando()){<p>Cargando prospectos…</p>}@else if(items().length===0){<div class="empty"><h2>Todavía no tienes prospectos</h2><p>Empieza registrando una lavandería potencial para LunaLav.</p><a routerLink="/marketing/prospectos/nuevo">Crear primer prospecto</a></div>}@else{<div class="row th"><span>Negocio</span><span>Distrito</span><span>Estado</span><span>Score</span><span>Próxima acción</span></div>@for(x of items();track x.id){<a class="row" [routerLink]="['/marketing/prospectos',x.id]"><span><b>{{x.nombreComercial}}</b><small>{{x.whatsapp||x.telefono||x.email||'Sin contacto'}}</small></span><span>{{x.distrito||'—'}}</span><span><i>{{x.estado.replaceAll('_',' ')}}</i></span><span><strong>{{x.score}}</strong><small>/100</small></span><span>{{x.proximoSeguimiento ? 'Programado' : 'Sin programar'}}</span></a>}<footer>{{total()}} prospectos registrados</footer>}</section>`,
styles:[`.head{display:flex;justify-content:space-between;gap:20px;align-items:start}.head span{font-size:11px;letter-spacing:1.4px;font-weight:900;color:#148acb}.head h1{margin:8px 0;font-size:30px}.head p{margin:0;color:#667e95;font-size:14px}.head>a,.empty a{background:#087cc1;color:#fff;text-decoration:none;border-radius:8px;padding:11px 14px;font-weight:800;font-size:13px}.filters{display:flex;gap:10px;margin:25px 0}.filters input,.filters select{background:#fff;border:1px solid #dce6ef;border-radius:8px;padding:11px;font-size:13px}.filters input{width:min(450px,100%)}.table{background:#fff;border:1px solid #e1e9f1;border-radius:12px;overflow:hidden}.row{display:grid;grid-template-columns:2fr 1fr 1.2fr .7fr 1.3fr;gap:10px;padding:14px 17px;align-items:center;border-bottom:1px solid #edf1f5;text-decoration:none;color:#21384f;font-size:13px}.row:not(.th):hover{background:#f6fbff}.th{font-size:11px;color:#7590a5;text-transform:uppercase;font-weight:800;background:#fafcff}.row span:first-child{display:grid;gap:3px}.row small{font-size:11px;color:#7890a4}.row i{font-style:normal;font-size:10px;font-weight:800;padding:5px 7px;border-radius:99px;background:#e5eff8;color:#25608e}.row strong{color:#087cc1}.empty{text-align:center;padding:64px 20px}.empty h2{font-size:19px}.empty p{color:#71869b;margin-bottom:24px}footer{padding:12px 17px;font-size:12px;color:#7890a4}@media(max-width:800px){.row{grid-template-columns:2fr 1fr .7fr}.row span:nth-child(2),.row span:nth-child(5){display:none}.head{align-items:center}.head p{display:none}}`]
}) export class MarketingProspectsComponent implements OnInit {private svc=inject(MarketingService);items=signal<Prospect[]>([]);total=signal(0);cargando=signal(true);q='';estado='';ngOnInit(){this.buscar();}buscar(){this.cargando.set(true);this.svc.prospects({q:this.q,estado:this.estado}).subscribe({next:x=>{this.items.set(x.items);this.total.set(x.total);this.cargando.set(false)},error:()=>this.cargando.set(false)});}}
